# Generated by Django 3.2.8 on 2022-06-15 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfiloproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='portfiloproject',
            name='portfiloFilter',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfilo',
            name='info',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='PortfiloProjectImage',
        ),
    ]
