# Generated by Django 3.2.8 on 2022-06-15 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_auto_20220615_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfiloproject',
            name='company',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
