# Generated by Django 3.2.8 on 2022-06-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_resume_resumeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockHero', models.BooleanField(default=True)),
                ('blockAbout', models.BooleanField(default=True)),
                ('blockFacts', models.BooleanField(default=True)),
                ('blockSkills', models.BooleanField(default=True)),
                ('blockResume', models.BooleanField(default=True)),
                ('blockPortfilo', models.BooleanField(default=True)),
                ('blockServices', models.BooleanField(default=True)),
                ('blockPartners', models.BooleanField(default=True)),
                ('blockContact', models.BooleanField(default=True)),
            ],
        ),
    ]
